language: php
php:
- '5.6'
notifications:
  slack:
    secure: yLlrDX7C9oF4ESAz86fslJfTusDY7PjQmcdNpVBkMq5Y1+/cOcJQO2kg2do/1Ka6zibo/yBIAC/+egobC9/J6381H4bSkNQfwTYD2e9Z4OhMQ5DvL+SEl3OiQ/usWoNmI7QagbyUE6kQt+61D3xZ70b9XfS19a4Qoku/EzrQHOM7flwqrQQ2iD4OjVxHtS7K76Pr/fmxu1HuLEZBqnENCV4hauCVnVoUNMEsK351+eDo9QXmedS9gyDmdmvUliGw7GaLB79uTsFvDm5YQ2Jqsv4pWAE2inMAy2XMFktop6dWXALOhjAEHhZY/O6DcNKp0Qbhx5HDCBTs9XX7anUWzoaUkgZA84iLAENlA529HvOBodPrOLTI7OfO/7MEX5P9Dg2yorTQGAgFkV5R8TKbNxuf17441wpOE8Q7MwbpXPgGmd8PmLGGinBicZvmJ/sze5vJwcbwwp238OseCcLYiuIBPgrCVsT8jizniQ6IvGoDigrD86uvVe+Bu8E6FhwORhvmXMiu64IfdlVFwLOvQK67aq4kdjMdEg3wbyM23k3aY8CPeSAfOkcJdiJsoivxIw4nlz7q0HUAvR7HD+hJCjwXpyPx7m4b6o3lj/3G7iQ9aCLMmsGOSf8YlChMSa/Zg5jxuTcBdU8IIlfZY+lihKj7tyWZFfKdw8qKwLmbDyo=
before_install:
# Get includes from the website's repo, per https://github.com/openva/rs-machine/issues/13
- git clone https://github.com/openva/richmondsunlight.com.git
- mkdir htdocs/includes
- cp richmondsunlight.com/htdocs/includes/*.php htdocs/includes/
- rm -Rf richmondsunlight.com
script:
- find . -name "*.php" -print0 |xargs -0 -n1 -P8 php -l
  && ./deploy/config_variables.sh
  && zip -qr latest *
  && mkdir -p upload
  && mv latest.zip upload/latest.zip
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: upload
  skip_cleanup: true
  on:
    branch: master
  bucket: deploy.api.richmondsunlight.com
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: deploy.api.richmondsunlight.com
  key: latest.zip
  bundle_type: zip
  application: RS-API
  deployment_group: RS-API-Fleet
  region: us-east-1
  on:
    branch: master
  wait-until-deployed: true
